# 指定 ClusterIP 為固定IP
# pod`s IP:80
# service`s IP(10.98.199.63):8081
# Node`s IP:30008
apiVersion: v1
kind: Service
metadata: 
  name: svc-2-httpd
  labels:
    app: svc-2-httpd
spec:
  type: NodePort
  clusterIP: 10.98.199.63
  ports:
  - port: 8081
    targetPort: 80
    nodePort: 30008
  selector:
    app: httpd-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-2
  labels:
    app: httpd-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-2
  template:
    metadata:
      labels:
        app: httpd-2
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
